### ISSUE TITLE
👀 Tracking: What peeps wanna do for Activity 3

### ISSUE THREAD

**Issue by reginawang99** [uclaacm/Playnet#132]
### Overview:
What peeps want do for A3
- @reginawang99 and @BryanPan342 can do what everyone else doesn't want / can't finish + high priorities

### Why this List:
- no accoutability/forcing ppl to finish what they were interested in!
- regina + bryan will play clean up / start from bottom of ppls lists 
    - we'll do other tix first 
#### Darren - @darren2hang:
- [x] finish up #112 (high pri)
- [ ] another animation one (eg #114)
- [ ] if time, interest in tutorial stuff > anime stuff (eg #111 ) 

#### Getty - @Phreakester:
- [x] finish up #99 
- [x] #101 

#### Trevor - @tr89on:
- [ ] #129 (high pri)
- [ ] #105
- [ ] #128

## Other tix:
bryan + regina should do these first

- [ ] #113 @reginawang99 
- [ ] #115 @BryanPan342 
- [ ] #106 @tr89on ty :)
- [ ] #136 @reginawang99 
--- 
This is a 👀 Tracking Issue

**Comment by reginawang99** [comment]
archiving this ticket
