### ISSUE TITLE
🚀 Feature: image preloading

### ISSUE THREAD

**Issue by reginawang99** [uclaacm/Playnet#162]
## Overview
pictures load slowly :0 :((

https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=508%3A40006
![image](https://user-images.githubusercontent.com/29292203/118348054-7b666b00-b4fc-11eb-969e-7e279ffb2479.png)

- apply load on 2nd page of intro
- apply load on first page of each activity

## Tasks
- [ ] Make animation screen #197 
- [ ] Preload while images are loading

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request
