### ISSUE TITLE
👀 Tracking: Changes for later

### ISSUE THREAD

**Issue by reginawang99** [uclaacm/Playnet#31]
### Overview:
List of changes requested or to be added later (blocked)
### Checklist:
- [ ] try thinner footer -> more content space available (request from designers)
- [ ] change image names for lottie to be more descriptive
- [ ] compress images so they smaller & change datacenter AE for new images

--- 
This is a 👀 Tracking Issue
